#!/bin/bash

### This script is called after the user uninstalls the application.
#!/bin/bash

TEST_FILE="${TRIM_PKGVAR}/test.log"

# 获取用户在向导中的选择
DATA_ACTION="$wizard_data_action"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${TEST_FILE}
}

log_msg "TRIM_DATA_SHARE_PATHS：$TRIM_DATA_SHARE_PATHS"
log_msg "TRIM_TEMP_LOGFILE：$TRIM_TEMP_LOGFILE"
log_msg "TRIM_TEMP_UPGRADE_FOLDER：$TRIM_TEMP_UPGRADE_FOLDER"
log_msg "TRIM_PKGINST_TEMP_DIR：$TRIM_PKGINST_TEMP_DIR"
log_msg "TRIM_TEMP_TPKFILE：$TRIM_TEMP_TPKFILE"

# 根据用户选择执行相应逻辑
if [ "${DATA_ACTION}" = "delete" ]; then
  # 检查文件/目录是否存在后再删除
  if [ -f "$TRIM_PKGVAR/data.db" ]; then
      rm "$TRIM_PKGVAR/data.db"
      echo "文件已删除"
  fi
  if [ -d "$TRIM_PKGVAR" ]; then
      rm -rf "$TRIM_PKGVAR"
      echo "目录已删除"
  fi
else
    echo "保留数据..."
fi

exit 0